services:
  mysql:
    image: mysql:8.0
    container_name: fos-accountbook-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accountbook
      MYSQL_USER: accountbook_user
      MYSQL_PASSWORD: accountbook_password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - accountbook-network

volumes:
  mysql_data:
    driver: local
    name: fos-accountbook-mysql-data

networks:
  accountbook-network:
    driver: bridge
    name: fos-accountbook-network

