server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fos-accountbook-backend
  
  # 로컬 개발용 MySQL (Docker) 설정
  datasource:
    url: jdbc:mysql://localhost:3306/accountbook?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: accountbook_user
    password: accountbook_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway가 마이그레이션을 담당
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # Flyway 마이그레이션 설정 (로컬)
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: false  # 로컬에서만 clean 허용
  
  security:
    filter:
      dispatcher-types: async, error, request

# 로컬 개발용 JWT 설정
jwt:
  secret: local-development-secret-key-for-testing-purposes-only-do-not-use-in-production-256bits
  expiration: 86400000  # 24시간
  refresh-expiration: 604800000  # 7일

# SpringDoc OpenAPI 설정 (로컬 개발용)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true  # 로컬에서는 활성화
  swagger-ui:
    path: /swagger-ui.html
    enabled: true  # 로컬에서는 활성화
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    doc-expansion: none  # API 목록 기본 접힌 상태

# 로깅 설정은 logback-spring.xml에서 관리 (local 프로파일)

